// src/components/Legend/index.tsx
import React, { FC } from 'react';
import './style.scss';

export const Legend: FC = () => {
  return (
    <div className={'legendBoard'}>
      <div className={'textLine'}>
        <code>V</code> – add vertical rule
      </div>
      <div className={'textLine'}>
        <code>H</code> – add horizontal rule
      </div>
      <div className={'textLine'}>
        <code>Q</code> – remove all guides
      </div>
      <div className={'textLine'}>
        <code>←</code>,<code>↑</code>,<code>→</code>,<code>↓</code> – move cursor 1px (+<code>Shift</code> 10px)
      </div>
      <div className={'textLine'}>
        <code>Space</code> – toggle help
      </div>
    </div>
  );
};

// js/components/Legend.vue
<template>
  <div :class=$style.legend>
    <div :class=$style.textLine><code>V</code> - add vertical rule</div>
    <div :class=$style.textLine><code>H</code> - add horisontal rule</div>
    <div :class=$style.textLine><code>Q</code> - remove all guides</div>
    <div :class=$style.textLine><code>←</code>,<code>↑</code>,<code>→</code>,<code>↓</code> - move cursor 1px direction (+<code>Shift</code> 10px)</div>
  </div>
</template>

<script>
  export default {
    name: 'Legend'
  };
</script>

<style module>
  .legend {
    pointer-events: none;
    position: fixed;
    bottom: 0;
    right: 0;
    padding: 10px 20px;
    border-radius: 3px 0 0 0;
    background: #000000;
    color: #ffffff;
    max-width: 300px;
  }

  .textLine {
    line-height: 2;
  }

  .legend code {
    background: #ffffff;
    color: #000000;
    border-radius: 2px;
    margin: 0 2px;
  }
</style>
